import { Footer, Navigation } from '@/components';
import { motion } from 'framer-motion';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { useEffect, useState } from 'react';

interface ImageProps {
  filename: string;
}

export default function Photo() {
  const [images, setImages] = useState<ImageProps[]>([]);
  const router = useRouter();
  const { filename } = router.query;

  useEffect(() => {
    async function fetchImages() {
      const res = await fetch('/api/images');
      const filenames = await res.json();
      //@ts-ignore
      const images = filenames.map((filename: any) => ({ filename }));
      setImages(images);
    }
    fetchImages();
  }, []);

  return (
    <>
      <Head>
        <title>Brittani & Klaven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <header>
        <Navigation page="gallery" />
      </header> */}
      <motion.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
        className="bg-project-white min-h-screen flex items-center justify-center py-10 px-4"
      >
        <div className="mx-auto max-w-screen-2xl flex items-center justify-center">
          <div className="max-w-[725px]">
            <motion.div
              initial={{ y: 100, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              className="aspect-auto"
            >
              <img src={`/img/${filename}.webp`} alt={``} className="w-full h-full object-cover object-center" />
            </motion.div>
          </div>
        </div>
      </motion.main>
      {/* <Footer /> */}
    </>
  );
}
