import { ReactNode } from 'react';
import { Navigation } from '../navigation';
import { Hero } from '../hero';

interface LayoutProps {
  children: ReactNode;
}

export function Layout({ children }: LayoutProps) {
  return (
    <>
      {/* <Head>
        <title>Brittani & Klaven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <header>
        <Navigation />
      </header>
      <section>
        <Hero />
      </section>
      <main className="px-4 max-w-[1440px] mx-auto sm:px-6">{children}</main>
    </>
  );
}
