import { Navigation } from '@/components';
import Head from 'next/head';

export default function Details() {
  return (
    <>
      <Head>
        <title>Brittani & Klaven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation page="details" />
      </header>
      <section className="hero min-h-[50vh] bg-secondary">
        <div className="hero-content text-center min-w-full">
          <div className="max-w-md">
            <h1 className="text-7xl lg:text-[7rem] text-project-white">Reception</h1>
          </div>
        </div>
      </section>
      <main className="px-4 py-20 min-h-screen bg-project-white">
        <div className="flex flex-col items-center justify-center max-w-screen-2xl mx-auto">
          <div className="text-center text-gray-700">
            <h1 className="text-typography text-6xl lg:text-7xl">July 28, 2023</h1>
            <h2 className="sub-title pt-10 text-3xl uppercase font-semibold">Juliette</h2>
            <div className="pt-4">
              <p className="text-xl font-normal">6:00 PM - 11:00PM</p>
              <p className="text-xl font-normal">135 N. 5th Street</p>
              <p className="text-xl font-normal">Brooklyn, NY</p>
            </div>
            <div className="pt-8 max-w-lg">
              <p className="italic leading-8">Attire: Semi-Formal.</p>
            </div>

            <div className="pt-8 max-w-lg">
              <p className="text-base font-light text-gray-500 leading-8">
                Even though we made our vows in Paris, we would still like to celebrate our union with all of you! Our
                wedding reception, will be at the <span className="font-bold italic text-typography">Juliette</span> on{' '}
                <span className="font-bold italic text-typography">Friday, July 28th, 2023</span>. We respectfully ask
                that this be an <span className="font-bold">adult only</span> wedding reception (18+). We thank you for
                attending our reception.{' '}
                <span className="font-bold italic text-typography">Please RSVP by June 16th, 2023</span>
              </p>
              <div className="mt-8">
                <p className="italic">
                  **Please check this page frequently as it may be updated with more details in the coming weeks**
                </p>
              </div>
            </div>
            <div className="pt-8 mx-auto grid grid-cols-2 gap-3 max-w-sm">
              <button className="btn btn-outline rounded-none text-typography border-tertiary italic font-light hover:bg-primary hover:border-primary">
                Directions
              </button>
              <button className="btn btn-outline rounded-none border-tertiary italic font-light hover:bg-primary hover:border-primary">
                Add To Calander
              </button>
              {/* <button className="btn btn-outline">Rsvp</button> */}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
