import { Footer, Navigation } from '@/components';
import { motion } from 'framer-motion';
import Head from 'next/head';

export default function Gallery() {
  return (
    <>
      <Head>
        <title>Brittani & Klaven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation page="gallery" />
      </header>
      <motion.main
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
        className="bg-project-white min-h-screen"
      >
        <div className="flex flex-col items-center justify-center max-w-screen-2xl mx-auto h-screen">
          <div className="text-center text-gray-700">
            <h2 className="sub-title text-typography text-6xl lg:text-7xl">Pictures Coming Soon!</h2>
          </div>
        </div>
      </motion.main>
      <Footer />
    </>
  );
}
