import { Navigation } from '@/components';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Brittani & Klaven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>
        <div
          className="hero min-h-[75vh]"
          style={{
            backgroundImage: `url("/PortraitWeddingHERO.png")`,
          }}
        >
          {/* <div className="hero-overlay bg-opacity-60"></div> */}
          <div className="hero-content text-center text-neutral-content"></div>
        </div>
      </main>
    </>
  );
}
