import { Footer, Navigation } from '@/components';
import { motion } from 'framer-motion';
import Head from 'next/head';

export default function OurStory() {
  return (
    <>
      <Head>
        <title>Brittani & Klaven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation page="details" />
      </header>
      <motion.section
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.5 }}
        className="bg-project-white py-10 mt-14 min-h-[calc(100vh_-_120px)]"
      >
        <div className="block mb-5 px-5 pt-5 pb-0 max-w-[1190px] mx-auto sm:flex sm:items-center sm:justify-start  sm:px-10 sm:pt-4 sm:mb-10">
          <div className="min-h-[69.47vh] relative sm:inline-block sm:align-middle sm:min-w-[430px] sm:w-[min(100%, 430px)] sm:min-h-[645px]">
            <div className="our-story-img-container early_dating_one absolute bg-cover top-0 left-0 bottom-0 filter brightness-[88%] saturate-[90%] hue-rotate-0 w-full" />
          </div>

          <div className="text-typography mt-10 my-5 mx-auto sm:mx-0 max-w-[90%] sm:px-10  sm:justify-center sm:inline-flex sm:flex-col sm:max-w-[500px]">
            <h1 className="text-4xl text-center sm:text-left">How We Met</h1>
            <div className="mt-4 align-top text-gray-500 space-y-5">
              <p className="text-center text-base font-light leading-relaxed sm:text-left">
                Klaven came across Brittani&apos;s profile on Plenty Of Fish (POF) and slid into her DMs with
                compliments of her beauty. They quickly hit it off and went on their first date at a trendy Peruvian
                restaurant in Chelsea. Little did he know, she had only created her account, because her friends had
                pressured her into trying online dating. So Klaven and Brittani met with a little luck.
              </p>
              <p className="text-center text-base font-light leading-relaxed sm:text-left">
                As they continued to date, Klaven realized that Brittani was the one for him when she cooked
                Thanksgiving dinner for him because she felt bad that he had to work on the holiday. Her kindness and
                compassion left a lasting impression on him, and he knew she was a keeper.
              </p>

              <p className="text-center text-base font-thin leading-relaxed sm:text-left">
                After a few Baecations, and dozens of Bottomless Brunches together. They are grateful for that chance
                encounter that brought them together and for the love and happiness they share.
              </p>
            </div>
          </div>
        </div>
        <div className="block mb-5 px-5 pt-5 pb-0 max-w-[1190px] mx-auto sm:flex sm:flex-row-reverse sm:items-center sm:justify-start  sm:px-10 sm:pt-4 sm:mb-10">
          <div className="min-h-[69.47vh] relative sm:inline-block sm:align-middle sm:min-w-[430px] sm:w-[min(100%, 430px)] sm:min-h-[645px]">
            <div className="our-story-img-container proposal-img absolute bg-cover top-0 left-0 bottom-0 filter brightness-[88%] saturate-[90%] hue-rotate-0 w-full" />
          </div>

          <div className="text-typography  mt-10 my-5 mx-auto sm:mx-0 max-w-[90%] sm:px-10  sm:justify-center sm:inline-flex sm:flex-col sm:max-w-[500px]">
            <h1 className="text-4xl text-center sm:text-right">The Proposal</h1>
            <div className="mt-4 align-top text-gray-500 space-y-5">
              <p className="text-center text-base font-light leading-relaxed sm:text-right">
                Klaven had been thinking about proposing to Brittani for some time, and with her birthday coming up, he
                knew it was the perfect opportunity. He enlisted the help of Brittani&apos;s friends, Olga and
                Elisabetta, to help him plan the perfect proposal.
              </p>
              <p className="text-center text-base font-light leading-relaxed sm:text-right">
                Klaven and Betta planned to scour Brooklyn Bridge park for the perfect spot, luckily Betta found it
                within a few steps. They came across the beautiful heart statue at the entrance of the Time Out market.
                It was perfect. Klaven felt relieved that he had found the perfect spot, with the help of Betta.
              </p>

              <p className="text-center text-base font-thin leading-relaxed sm:text-right">
                The night before the proposal, Klaven was shook! Brittani went on a girl&apos;s night out with her squad
                for her birthday (The Goons, as Klay calls them) and when she got home, she spent all night building a
                new bookshelf. Klaven was worried she&apos;d be too tired for their date. Luckily, Brittani was ok, and
                didn&apos;t flake. The next day, after a delicious brunch in the city, Klaven took Brittani to the Time
                Out market and proposed to her. She said yes! To her surprise, her friends were all there to celebrate.
              </p>
            </div>
          </div>
        </div>
        <div className="block mb-5 px-5 pt-5 pb-0 max-w-[1190px] mx-auto sm:flex sm:items-center sm:justify-start  sm:px-10 sm:pt-4 sm:mb-10">
          <div className="min-h-[69.47vh] relative sm:inline-block sm:align-middle sm:min-w-[430px] sm:w-[min(100%, 430px)] sm:min-h-[645px]">
            <div className="our-story-img-container how-we-met-img absolute bg-cover top-0 left-0 bottom-0 filter brightness-[88%] saturate-[90%] hue-rotate-0 w-full" />
          </div>

          <div className="text-typography  mt-10 my-5 mx-auto sm:mx-0 max-w-[90%] sm:px-10  sm:justify-center sm:inline-flex sm:flex-col sm:max-w-[500px]">
            <h1 className="text-4xl text-center sm:text-left">The Elopment</h1>
            <div className="mt-4 align-top text-gray-500 space-y-5">
              <p className="text-center text-base font-light leading-relaxed sm:text-left">
                Brittani had always dreamed of eloping to Paris, and Klaven was more than happy to make her dream come
                true. When he proposed, she knew exactly where she wanted to go to elope, and they began planning their
                trip to the city of love.
              </p>
              <p className="text-center text-base font-light leading-relaxed sm:text-left">
                During their week-long trip to Paris, Klaven and Brittani visited Disneyland Paris where they enjoyed
                several attractions and shows. They rode some of the rides and watched the famous Lion King show, which
                left them feeling nostalgic and happy.
              </p>
              <p className="text-center text-base font-thin leading-relaxed sm:text-left">
                In a romantic and intimate ceremony overlooking the Eiffel Tower, Klaven and Brittani exchanged their
                vows and became husband and wife. It was everything Brittani had always dreamed of, and she was grateful
                to be able to share such a special moment with the love of her life.
              </p>
              <p className="text-center text-base font-thin leading-relaxed sm:text-left">
                Although they eloped, Klaven and Brittani still plan to celebrate their love with their friends and
                family. They are excited to throw a big party and share their happiness with their loved ones.
              </p>
            </div>
          </div>
        </div>
      </motion.section>
      <Footer />
    </>
  );
}
