import { Footer, Navigation } from '@/components';
import Head from 'next/head';
import Link from 'next/link';

export default function Gallery() {
  return (
    <>
      <Head>
        <title>Brittani & Klaven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation page="gallery" />
      </header>
      <section className="hero min-h-[50vh] bg-secondary">
        <div className="hero-content text-center">
          <div className="max-w-full">
            <h1 className="text-4xl lg:text-6xl text-project-white">Registry</h1>
          </div>
        </div>
      </section>
      <main className="px-10 pt-20 pb-10 bg-project-white">
        <div className="flex flex-col items-center justify-center max-w-screen-2xl mx-auto">
          <div>
            <h1 className="sub-title text-2xl sm:text-3xl text-center">Thank you from the bottom of our hearts!</h1>
          </div>
        </div>
      </main>
      <section className="py-20 px-10 max-w-5xl mx-auto min-h-[40vh]">
        <div className="grid gap-8 sm:grid-cols-2 min-w-lg mx-auto">
          <Link
            href="https://registry.theknot.com/klaven-jones-brittani-smith-july-2023-ny/59489454"
            target="_blank"
            className="btn btn-outline rounded-none flex items-center justify-center min-h-[300px] border-2 text-typography border-tertiary hover:bg-primary hover:border-primary"
          >
            <p className="uppercase tracking-widest">New Home Fund</p>
          </Link>
          <Link
            href="https://www.amazon.com/wedding/klaven-jones-brittani-smith-jones--july-2023/registry/3E14FD53HW84W"
            target="_blank"
            className="btn btn-outline rounded-none flex items-center justify-center min-h-[300px] border-2 text-typography border-tertiary hover:bg-primary hover:border-primary"
          >
            <p className="uppercase tracking-widest">Amazon</p>
          </Link>
        </div>
      </section>
      <Footer />
    </>
  );
}
